# Generated by Django 5.1.4 on 2025-01-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
